### ISSUE TITLE
Installation in Plone 4.1

### ISSUE THREAD

**Issue by realefab** [collective/mr.migrator#7]
Hi all,
to install the product in a Plone 4.1 I had to add

```
<include package="Products.CMFCore" />
```

into the file `mr.migrator/mr/migrator/browser/configure.zcml`
Is it the correct way?
My source was http://plone.org/documentation/manual/upgrade-guide/version/upgrading-plone-4.0-to-4.1/updating-add-on-products-for-plone-4.1/changing-dependencies-from-plone-to-products.cmfplone

**Comment by sunew** [comment]
fixed in #8 and merged
